# Generated by Django 5.1.3 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constitutionalarticle',
            options={'ordering': ['part', 'type', 'article_number']},
        ),
        migrations.AddField(
            model_name='constitutionalarticle',
            name='part',
            field=models.IntegerField(choices=[(5, 'Part 5'), (6, 'Part 6')], default=5),
        ),
        migrations.AddField(
            model_name='constitutionalarticle',
            name='type',
            field=models.CharField(choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], default='LEG', max_length=4),
        ),
    ]
