# Generated by Django 5.1.2 on 2024-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_simplifiedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedarticle',
            name='part',
            field=models.IntegerField(blank=True, choices=[(5, 'Part 5'), (6, 'Part 6')], null=True),
        ),
        migrations.AddField(
            model_name='simplifiedarticle',
            name='type',
            field=models.CharField(blank=True, choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], max_length=4, null=True),
        ),
    ]
