# Generated by Django 5.1.2 on 2024-11-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0002_article_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_case_index', models.IntegerField(default=0)),
                ('round_start_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='housie_consti.gameroom')),
            ],
        ),
    ]
