# Generated by Django 5.1.2 on 2024-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0006_gameroom_player_points_gameroom_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='selected_cards',
            field=models.JSONField(default=dict),
        ),
    ]
