# Generated by Django 5.1.2 on 2024-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0008_alter_gameroom_player_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='full_housie_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
