# Generated by Django 5.1.2 on 2024-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0011_gameroom_selection_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='selection_times',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='wrong_selections',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
