# Generated by Django 5.1.3 on 2024-12-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0013_remove_case_articles_involved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
        migrations.RemoveField(
            model_name='case',
            name='year',
        ),
    ]
