# Generated by Django 5.1.3 on 2024-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0014_alter_case_options_remove_case_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
