# Generated by Django 5.1.2 on 2024-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0017_remove_gameroom_full_housie_achieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_case_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
