# Generated by Django 5.1.2 on 2024-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0022_merge_0019_article_part_article_type_0021_playerscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='first_five_points',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='first_five_winner',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_points',
        ),
        migrations.DeleteModel(
            name='PlayerScore',
        ),
    ]
