# Generated by Django 5.1.2 on 2024-12-06 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0024_playerpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerpoints',
            unique_together={('room', 'player')},
        ),
    ]
