# Generated by Django 5.1.2 on 2024-11-30 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheel', '0002_add_constitution_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_spin_refill',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_spin_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='max_spins',
            field=models.IntegerField(default=10),
        ),
    ]
