# Generated by Django 5.1.2 on 2024-11-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheel', '0003_add_constitution_cards'),
        ('spinwheel', '0004_remove_playerprofile_last_spin_time'),
    ]

    operations = [
    ]
