# Generated by Django 5.1.3 on 2024-11-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0006_cellhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellhistory',
            name='answer_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='question_generated_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_generated', to='snake_ladder.cell'),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='time_to_answer',
            field=models.IntegerField(null=True),
        ),
    ]
