# Generated by Django 5.1.3 on 2024-12-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0014_cellhistory_dice_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Educational content')),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('part', models.IntegerField(choices=[(5, 'Part 5'), (6, 'Part 6')], default=5)),
                ('type', models.CharField(choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], default='LEG', max_length=4)),
            ],
            options={
                'ordering': ['part', 'type'],
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='current_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_on_cell', to='snake_ladder.cellcontent'),
        ),
    ]
