# Generated by Django 5.1.3 on 2024-12-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0018_gameroom_points_playeroverallpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_content_part',
            field=models.IntegerField(choices=[(5, 'Part 5'), (6, 'Part 6')], null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_content_type',
            field=models.CharField(choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], max_length=4, null=True),
        ),
    ]
