# Generated by Django 5.1.2 on 2024-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0005_simplifiedarticle_article_title'),
        ('flip_card', '0002_userprogress_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('part', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('articles', models.ManyToManyField(to='dbs.simplifiedarticle')),
            ],
        ),
    ]
