# Generated by Django 5.1.2 on 2024-11-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheel', '0003_remove_playerprofile_last_spin_refill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_spin_time',
        ),
    ]
