# Generated by Django 5.1.2 on 2024-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_alter_constitutionalarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifiedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=10)),
                ('original_content', models.TextField()),
                ('simplified_content', models.CharField(max_length=200)),
                ('last_simplified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
