# Generated by Django 5.1.2 on 2024-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0004_simplifiedarticle_part_simplifiedarticle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedarticle',
            name='article_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
