# Generated by Django 5.1.2 on 2024-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0002_article_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='article_selection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='case_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
