# Generated by Django 5.1.3 on 2024-11-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0003_gameroom_article_selection_gameroom_case_order'),
        ('housie_consti', '0003_gamestate'),
    ]

    operations = [
    ]
