# Generated by Django 5.1.3 on 2024-12-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0009_gameroom_full_housie_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='wrong_selections',
            field=models.JSONField(default=dict),
        ),
    ]
