# Generated by Django 5.1.2 on 2024-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0019_gameroom_first_five_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='first_five_points',
            field=models.IntegerField(default=15),
        ),
    ]
