# Generated by Django 5.1.3 on 2024-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('content', models.TextField(help_text='Educational content for this cell')),
                ('cell_type', models.CharField(choices=[('NORMAL', 'Normal Cell'), ('SNAKE', 'Snake Head'), ('LADDER', 'Ladder Bottom')], default='NORMAL', max_length=10)),
                ('destination', models.IntegerField(blank=True, help_text='Destination cell number for snakes and ladders', null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
