# Generated by Django 5.1.3 on 2024-11-17 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0002_gameroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
