# Generated by Django 5.1.3 on 2024-11-29 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0008_gameroom_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cellhistory',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='selected_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='topic_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='cellhistory',
            index=models.Index(fields=['player', 'answer_correct'], name='snake_ladde_player__dc9374_idx'),
        ),
    ]
