# Generated by Django 5.1.3 on 2024-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0009_cellhistory_correct_answer_cellhistory_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellhistory',
            name='question_generated_from',
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='cumulative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cellhistory',
            name='moves_after_answer',
            field=models.IntegerField(null=True),
        ),
    ]
