# Generated by Django 5.1.3 on 2024-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0010_remove_cellhistory_question_generated_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellhistory',
            name='options',
            field=models.TextField(null=True),
        ),
    ]
