# Generated by Django 5.1.3 on 2024-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0011_cellhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic category for this cell', max_length=100, null=True),
        ),
    ]
