# Generated by Django 5.1.3 on 2024-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0013_cellhistory_source_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellhistory',
            name='dice_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
