# Generated by Django 5.1.2 on 2024-12-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheel', '0001_cardcombo_playercomboprogress'),
        ('spinwheel', 'update_card_rarities'),
    ]

    operations = [
    ]
