# Generated by Django 5.1.2 on 2024-12-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
