# Generated by Django 5.1.3 on 2024-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
