# Generated by Django 5.1.3 on 2024-12-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlatPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_part', models.IntegerField(choices=[(5, 'Part 5'), (6, 'Part 6')], default=5)),
                ('current_type', models.CharField(choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], default='JUD', max_length=4)),
                ('completed_checkpoints', models.JSONField(default=dict)),
                ('total_points', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('snake_ladder_points', models.IntegerField(default=0)),
                ('housie_points', models.IntegerField(default=0)),
                ('spinwheel_points', models.IntegerField(default=0)),
                ('flipcard_points', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
