# Generated by Django 5.1.2 on 2024-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Image related to the event', null=True, upload_to='timeline_images/'),
        ),
    ]
