# Generated by Django 5.1.2 on 2024-12-08 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_timelineevent_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order', 'year']},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='date',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(default=1950, help_text='Year of the constitutional event', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
