# Generated by Django 5.1.2 on 2024-11-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0004_merge_20241130_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='article_selection',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
