# Generated by Django 5.1.2 on 2024-12-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0005_alter_gameroom_article_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player_points',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='points_awarded',
            field=models.JSONField(default=dict),
        ),
    ]
