# Generated by Django 5.1.2 on 2024-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0007_gameroom_selected_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='player_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='points_awarded',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
