# Generated by Django 5.1.3 on 2024-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0010_gameroom_wrong_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='selection_times',
            field=models.JSONField(default=dict),
        ),
    ]
