# Generated by Django 5.1.3 on 2024-12-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0012_alter_gameroom_selection_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='articles_involved',
        ),
    ]
