# Generated by Django 5.1.3 on 2024-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0015_article_article_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='article',
        ),
        migrations.AddField(
            model_name='case',
            name='articles',
            field=models.ManyToManyField(related_name='cases', to='housie_consti.article'),
        ),
    ]
