# Generated by Django 5.1.2 on 2024-12-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0016_remove_case_article_case_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='full_housie_achieved',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_points',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='points_awarded',
        ),
    ]
