# Generated by Django 5.1.2 on 2024-12-06 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0018_gameroom_current_case_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='first_five_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='first_five_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_five_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
