# Generated by Django 5.1.2 on 2024-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0019_article_part_article_type'),
        ('housie_consti', '0021_playerscore'),
    ]

    operations = [
    ]
