# Generated by Django 5.1.2 on 2024-12-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0025_alter_playerpoints_unique_together'),
        ('housie_consti', '0025_cleanup_duplicate_playerpoints'),
    ]

    operations = [
    ]
