# Generated by Django 5.1.2 on 2024-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0026_merge_20241206_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='round_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
