# Generated by Django 5.1.2 on 2024-12-06 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0027_alter_gamestate_round_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerpoints',
            unique_together={('player', 'room')},
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='avg_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='round_start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
