# Generated by Django 5.1.3 on 2024-12-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0028_alter_playerpoints_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_number'], 'verbose_name': 'Constitutional Article', 'verbose_name_plural': 'Constitutional Articles'},
        ),
    ]
