# Generated by Django 5.1.2 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0029_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='article_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
