# Generated by Django 5.1.2 on 2024-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0030_case_article_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='article_metadata',
        ),
        migrations.AddField(
            model_name='case',
            name='part',
            field=models.IntegerField(blank=True, choices=[(5, 'Part 5'), (6, 'Part 6')], null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], max_length=4, null=True),
        ),
    ]
