# Generated by Django 5.1.2 on 2024-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie_consti', '0031_remove_case_article_metadata_case_part_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
