from django.urls import path
from . import views

app_name = 'housie_consti'

urlpatterns = [
    path('', views.create_room, name='create_room'),
    path('join/<uuid:room_id>/', views.join_room, name='join_room'),
    path('room/<uuid:room_id>/', views.room_detail, name='room_detail'),
    path('room/<uuid:room_id>/<int:part>/<str:type>/', views.room_detail, name='room_detail_filtered'),
    path('game/<uuid:room_id>/', views.game_board, name='game_board'),
    path('housie-basic/<uuid:room_id>/', views.housie_basic, name='housie_basic'),
    path('game-state/<uuid:room_id>/', views.get_game_state, name='game_state'),
    path('manage/', views.manage_content, name='manage_content'),
    path('manage/articles/', views.manage_articles, name='manage_articles'),
    path('manage/cases/', views.manage_cases, name='manage_cases'),
    path('add/article/', views.add_article, name='add_article'),
    path('edit/article/<int:article_id>/', views.edit_article, name='edit_article'),
    path('delete/article/<int:article_id>/', views.delete_article, name='delete_article'),
    path('add/case/', views.add_case, name='add_case'),
    path('edit/case/<int:case_id>/', views.edit_case, name='edit_case'),
    path('delete/case/<int:case_id>/', views.delete_case, name='delete_case'),
    path('get-selected-cards/<uuid:room_id>/', views.get_selected_cards, name='get_selected_cards'),
    path('mark-card-selected/<uuid:room_id>/', views.mark_card_selected, name='mark_card_selected'),
    path('api/room/<uuid:room_id>/state/', views.room_state, name='room_state'),
    path('api/room/<uuid:room_id>/start/', views.start_game, name='start_game'),
    path('check-selected-cards/<uuid:room_id>/', views.check_selected_cards, name='check_selected_cards'),
    path('leaderboard/<uuid:room_id>/', views.leaderboard, name='leaderboard'),
    path('record-wrong-selection/<uuid:room_id>/', views.handle_wrong_selection, name='record_wrong_selection'),
    path('record-selection-time/<uuid:room_id>/', views.record_selection_time, name='record_selection_time'),
    path('check-selection/<uuid:room_id>/', views.check_selection, name='check_selection'),
    path('room/<uuid:room_id>/analysis/', views.game_analysis, name='game_analysis'),
    path('get-game-state/<uuid:room_id>/', views.get_game_state, name='get_game_state'),
    path('select-article/<uuid:room_id>/', views.select_article, name='select_article'),
    path('update-points/<uuid:room_id>/', views.update_points, name='update_points'),
    path('advance-case/<uuid:room_id>/', views.advance_case, name='advance_case'),
    path('intro/', views.housie_intro, name='housie_intro'),
    path('intro/<int:part>/<str:type>/', views.housie_intro, name='housie_intro_filtered'),
    path('cases/<int:part>/<str:type>/', views.filtered_cases, name='filtered_cases'),
    path('game/<uuid:room_id>/<int:part>/<str:type>/', views.game_board, name='game_board_filtered'),
    path('api/room/<uuid:room_id>/start/<int:part>/<str:type>/', views.start_game, name='start_game_filtered'),
    path('filtered-game/', views.filtered_game, name='filtered_game'),
    path('preview/<int:part>/<str:type>/', views.preview_filtered_cases, name='preview_filtered_cases'),
]
