# Generated by Django 5.1.3 on 2024-12-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerplatpoints',
            options={'verbose_name': 'Player Platform Points', 'verbose_name_plural': 'Player Platform Points'},
        ),
    ]
