# Generated by Django 5.1.3 on 2024-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0002_alter_playerplatpoints_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerplatpoints',
            name='flipcard_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='flipcard_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='housie_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='housie_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='snake_ladder_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='snake_ladder_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='spinwheel_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='spinwheel_wins',
            field=models.IntegerField(default=0),
        ),
    ]
