# Generated by Django 5.1.3 on 2024-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0003_playerplatpoints_flipcard_games_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerplatpoints',
            old_name='spinwheel_points',
            new_name='common_cards',
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='epic_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='legendary_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='rare_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='spinwheel_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerplatpoints',
            name='total_cards',
            field=models.IntegerField(default=0),
        ),
    ]
