# Generated by Django 5.1.3 on 2024-12-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0012_cell_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellhistory',
            name='source_cell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
