# Generated by Django 5.1.3 on 2024-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_ladder', '0015_cellcontent_cell_current_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellcontent',
            name='part',
            field=models.IntegerField(blank=True, choices=[(5, 'Part 5'), (6, 'Part 6')], null=True),
        ),
        migrations.AlterField(
            model_name='cellcontent',
            name='type',
            field=models.CharField(blank=True, choices=[('JUD', 'Judiciary'), ('LEG', 'Legislative'), ('EXEC', 'Executive')], max_length=4, null=True),
        ),
    ]
